[package]
name = "astatine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
java-desc = "0.1.1"
jni = "0.19.0"
